--- #YAML:1.0
name:                Test-Smoke
version:             1.20.03
abstract:            The Perl core test smoke suite
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    File::Spec:                    0.82
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - H.Merijn Brand <h.m.brand@hccnet.nl>, Nicholas Clark <nick@plum.flirble.org> and Abe Timmerman <abeltje@cpan.org>
